name: "Deploy to sandbox"
concurrency: sandbox_deploy
on:
  workflow_call: 
  push:
    branches: [sandbox]

jobs:
  deploy:
    name: Deploy to sandbox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: echo "Simulating build"

      - name: Deploy
        run: echo "Simulating deploy"
