name: "Fast Merge sandbox"
concurrency: sandbox_deploy
on:
  issue_comment:
    types: [created]

jobs:
  fast-merge-sandbox:
    if: contains(github.event.comment.body, '/fast-merge sandbox') && ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.1
      - name: Print Outputs
        run: echo ${{join(steps.branch-name.outputs.*, '\n')}}
      - uses: actions/checkout@v1
        with:
          ref: sandbox
      - name: Config git CLI
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.event.repository.full_name}}.git
          git config --global user.email "fast-merge@github.com"
          git config --global user.name "GitHub Fast Merge Action"
          git config pull.rebase false
      - name: Merge Branch
        run: |
          git pull origin ${{steps.branch-name.outputs.current_branch}}

      - name: Push Branch
        run: |
          git push origin sandbox

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Deploy to sandbox with success !'
          pr_number: ${{github.event.issue.number}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}