name: "Fast Merge sandbox"
concurrency: sandbox_deploy
on:
  issue_comment:
    types: [created]

jobs:
  fast-merge-sandbox:
    if: contains(github.event.comment.body, '/fast-merge sandbox') && ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR ref
        id: branch-name
        run: |
          URI=https://api.github.com
          API_HEADER="Accept: application/vnd.github.v3+json"
          AUTH_HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          PR_NUMBER=${{github.event.issue.number}}
          REPO_FULLNAME=${{github.event.repository.full_name}}
          pr_resp=$(curl -X GET -s -H "${AUTH_HEADER}" -H "${API_HEADER}" \
            "${URI}/repos/$REPO_FULLNAME/pulls/$PR_NUMBER")
          HEAD_REF=$(echo "$pr_resp" | jq -r .head.ref)
          echo "::set-output name=PR_HEAD_REF::$HEAD_REF"
      - uses: actions/checkout@v1
        with:
          ref: sandbox
      - name: Config git CLI
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.event.repository.full_name}}.git
          git config --global user.email "fast-merge@github.com"
          git config --global user.name "GitHub Fast Merge Action"
          git config pull.rebase false
      - name: Merge Branch
        run: |
          git pull origin ${{steps.branch-name.outputs.PR_HEAD_REF}}

      - name: Push Branch
        run: |
          git push origin sandbox

      - name: Deploy
        uses: ./.github/workflows/deploy-sandbox.yaml

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1.1.0
        with:
          message: 'Deploy to sandbox with success !'
          pr_number: ${{github.event.issue.number}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}